# Generated by Django 5.2.15 on 2026-07-03 03:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriSampah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga_beli_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok_terkini_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MitraPengepul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kontak', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('poin_dibutuhkan', models.IntegerField()),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('nasabah', 'Nasabah'), ('petugas', 'Petugas'), ('admin', 'Admin Aplikasi'), ('koordinator', 'Koordinator')], default='nasabah', max_length=20)),
                ('nik', models.CharField(blank=True, max_length=16)),
                ('no_hp', models.CharField(blank=True, max_length=15)),
                ('alamat', models.TextField(blank=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('poin', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PenarikanSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('selesai', 'Selesai')], default='menunggu', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keluhan', models.TextField()),
                ('status', models.CharField(choices=[('terbuka', 'Terbuka'), ('ditutup', 'Ditutup')], default='terbuka', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penjemputan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimasi_berat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alamat_jemput', models.TextField()),
                ('jadwal', models.DateTimeField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('dijadwalkan', 'Dijadwalkan'), ('dijemput', 'Dijemput'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjemputan_nasabah', to=settings.AUTH_USER_MODEL)),
                ('petugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penjemputan_petugas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PenjualanMitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat_jual_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('harga_jual_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_penjualan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.kategorisampah')),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mitrapengepul')),
            ],
        ),
        migrations.CreateModel(
            name='PenukaranPoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('selesai', 'Selesai')], default='menunggu', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.reward')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiSetoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('total_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='selesai', max_length=20)),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setoran_nasabah', to=settings.AUTH_USER_MODEL)),
                ('petugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setoran_petugas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSetoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('harga_saat_itu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.kategorisampah')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.transaksisetoran')),
            ],
        ),
    ]
