# Generated by Django 5.2.15 on 2026-07-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjemputan',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('dijadwalkan', 'Dijadwalkan'), ('dalam_perjalanan', 'Dalam Perjalanan'), ('dijemput', 'Dijemput'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20),
        ),
    ]
