# Generated by Django 5.2.15 on 2026-07-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanInstitusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_institusi', models.CharField(max_length=255)),
                ('alamat', models.TextField(blank=True, default='')),
                ('kontak', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('jam_operasional', models.CharField(blank=True, default='', max_length=255)),
                ('pengumuman', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Pengaturan Institusi',
                'verbose_name_plural': 'Pengaturan Institusi',
            },
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('aktif', models.BooleanField(default=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-tanggal'],
            },
        ),
    ]
