# Generated by Django 5.2.15 on 2026-07-08 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pengaturan_institusi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatHarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_lama', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_baru', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_berlaku', models.DateTimeField(auto_now_add=True)),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_harga_diubah', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_harga', to='api.kategorisampah')),
            ],
            options={
                'ordering': ['-tanggal_berlaku'],
            },
        ),
    ]
