# Generated by Django 5.2.15 on 2026-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_riwayat_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setuju_kebijakan_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tanggal_persetujuan_kebijakan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
