# Generated by Django 5.2.15 on 2026-07-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_privacy_consent'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorisampah',
            options={'verbose_name_plural': 'Kategori Sampah'},
        ),
        migrations.AlterModelOptions(
            name='penarikansaldo',
            options={'verbose_name_plural': 'Penarikan Saldo'},
        ),
        migrations.AlterModelOptions(
            name='pengaduan',
            options={'verbose_name_plural': 'Pengaduan'},
        ),
        migrations.AlterModelOptions(
            name='transaksisetoran',
            options={'verbose_name_plural': 'Transaksi Setoran'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='kategorisampah',
            index=models.Index(fields=['nama'], name='api_kategor_nama_889803_idx'),
        ),
        migrations.AddIndex(
            model_name='penarikansaldo',
            index=models.Index(fields=['status'], name='api_penarik_status_6997e8_idx'),
        ),
        migrations.AddIndex(
            model_name='penarikansaldo',
            index=models.Index(fields=['nasabah'], name='api_penarik_nasabah_41d142_idx'),
        ),
        migrations.AddIndex(
            model_name='penarikansaldo',
            index=models.Index(fields=['tanggal'], name='api_penarik_tanggal_ddc1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='pengaduan',
            index=models.Index(fields=['status'], name='api_pengadu_status_f88160_idx'),
        ),
        migrations.AddIndex(
            model_name='pengaduan',
            index=models.Index(fields=['nasabah'], name='api_pengadu_nasabah_a28d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='penjemputan',
            index=models.Index(fields=['status'], name='api_penjemp_status_530e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='penjemputan',
            index=models.Index(fields=['nasabah'], name='api_penjemp_nasabah_518eca_idx'),
        ),
        migrations.AddIndex(
            model_name='penjemputan',
            index=models.Index(fields=['petugas'], name='api_penjemp_petugas_9858a8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksisetoran',
            index=models.Index(fields=['tanggal'], name='api_transak_tanggal_555165_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksisetoran',
            index=models.Index(fields=['nasabah'], name='api_transak_nasabah_367b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='api_user_role_9b9076_idx'),
        ),
    ]
