# Generated by Django 5.2.15 on 2026-07-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_kategorisampah_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penarikansaldo',
            name='nama_bank',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='penarikansaldo',
            name='nama_pemilik_rekening',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='penarikansaldo',
            name='no_rekening',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
