# Generated by Django 5.2.15 on 2026-07-10 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transfer_account_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('setoran', 'Setoran'), ('penjemputan', 'Penjemputan'), ('penarikan', 'Penarikan Saldo'), ('penukaran', 'Penukaran Poin'), ('pengaduan', 'Pengaduan'), ('sistem', 'Sistem')], default='sistem', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Penerima notifikasi', on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='api_notifik_user_id_4344ad_idx'), models.Index(fields=['created_at'], name='api_notifik_created_bf0c50_idx')],
            },
        ),
    ]
