# Generated by Django 5.2.15 on 2026-07-14 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_notifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontenEdukasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField(help_text='Isi konten/panduan edukasi')),
                ('aktif', models.BooleanField(default=True)),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tampil (ascending)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori_terkait', models.ForeignKey(blank=True, help_text='Kategori sampah terkait (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konten_edukasi', to='api.kategorisampah')),
            ],
            options={
                'verbose_name': 'Konten Edukasi',
                'verbose_name_plural': 'Konten Edukasi',
                'ordering': ['urutan', 'created_at'],
            },
        ),
    ]
