# Generated by Django 5.2.15 on 2026-07-14 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_konten_edukasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatharga',
            name='tanggal_berlaku',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Harga mulai berlaku pada tanggal ini (min H+3 dari penetapan)'),
        ),
    ]
