# Generated by Django 5.2.15 on 2026-07-14 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_riwayat_harga_tanggal_berlaku'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rt',
            field=models.CharField(blank=True, default='', help_text='RT (opsional)', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='rw',
            field=models.CharField(blank=True, default='', help_text='RW (opsional)', max_length=10),
        ),
        migrations.CreateModel(
            name='WilayahLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelurahan', models.CharField(db_index=True, max_length=100)),
                ('rt', models.CharField(blank=True, default='', help_text='RT (opsional)', max_length=10)),
                ('rw', models.CharField(blank=True, default='', help_text='RW (opsional)', max_length=10)),
                ('aktif', models.BooleanField(default=True, help_text='Wilayah yang masih dilayani')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wilayah Layanan',
                'verbose_name_plural': 'Wilayah Layanan',
                'ordering': ['kelurahan', 'rt', 'rw'],
                'indexes': [models.Index(fields=['kelurahan'], name='api_wilayah_kelurah_c7f318_idx'), models.Index(fields=['aktif'], name='api_wilayah_aktif_8da869_idx')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='kelurahan',
            field=models.ForeignKey(blank=True, help_text='Kelurahan/kampung domisili (Fase 8.3)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penduduk', to='api.wilayahlayanan'),
        ),
    ]
