# Generated by Django 5.2.15 on 2026-07-14 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_wilayah_layanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='penarikansaldo',
            name='lampiran_ktp',
            field=models.FileField(blank=True, help_text='Lampiran KTP untuk penarikan besar ≥ Rp1.000.000 (Fase 8.4)', null=True, upload_to='lampiran_ktp/'),
        ),
        migrations.AddField(
            model_name='user',
            name='foto_ktp',
            field=models.FileField(blank=True, help_text='Foto KTP untuk verifikasi identitas (Fase 8.4)', null=True, upload_to='ktp/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nik_encrypted',
            field=models.TextField(blank=True, default='', help_text='NIK terenkripsi at-rest (Fase 8.4)'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Reset Password',
                'verbose_name_plural': 'Token Reset Password',
                'ordering': ['-created_at'],
            },
        ),
    ]
