# Generated by Django 5.2.15 on 2026-07-14 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fase8_4_identitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoinTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumber', models.CharField(choices=[('setoran', 'Setoran'), ('koreksi', 'Koreksi')], default='setoran', max_length=20)),
                ('jumlah', models.IntegerField(help_text='Jumlah poin (positif = diperoleh, negatif = hangus/dipakai)')),
                ('sisa', models.IntegerField(help_text='Sisa poin yang belum hangus/dipakai')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_kedaluwarsa', models.DateTimeField(help_text='Poin hangus jika melewati tanggal ini (1 tahun dari perolehan)')),
                ('is_expired', models.BooleanField(default=False, help_text='True jika poin sudah hangus oleh scheduled task')),
                ('setoran', models.ForeignKey(blank=True, help_text='Transaksi setoran asal (jika dari setoran)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poin_transaksi', to='api.transaksisetoran')),
                ('user', models.ForeignKey(help_text='Nasabah pemilik poin', on_delete=django.db.models.deletion.CASCADE, related_name='poin_transaksi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Poin',
                'verbose_name_plural': 'Riwayat Poin',
                'ordering': ['tanggal_dibuat'],
                'indexes': [models.Index(fields=['user', 'is_expired'], name='api_pointra_user_id_ba5669_idx'), models.Index(fields=['tanggal_kedaluwarsa'], name='api_pointra_tanggal_d94a0d_idx')],
            },
        ),
    ]
