# Generated by Django 5.2.15 on 2026-07-14 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fase8_5_poin_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='kategori',
            field=models.CharField(choices=[('setoran', 'Setoran'), ('penjemputan', 'Penjemputan'), ('penarikan', 'Penarikan Saldo'), ('penukaran', 'Penukaran Poin'), ('pengaduan', 'Pengaduan'), ('pengumuman', 'Pengumuman'), ('harga', 'Perubahan Harga'), ('sistem', 'Sistem')], default='sistem', max_length=20),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'indexes': [models.Index(fields=['user'], name='api_devicet_user_id_d47aee_idx')],
            },
        ),
    ]
