# Generated by Django 5.2.15 on 2026-08-11 02:08
# Renumbered from T2 0019_t2_phone_otp_verified → 0021 (after 0020_penukaran_poin_snapshot_status)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_penukaran_poin_snapshot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Koordinat lat profil (opsional, maps)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Koordinat lng profil (opsional, maps)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='patokan',
            field=models.CharField(blank=True, default='', help_text='Patokan lokasi / keterangan maps (opsional)', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='True jika nomor HP sudah diverifikasi OTP WhatsApp (T2/T10)'),
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('password_reset', 'Reset Password'), ('phone_verify', 'Verifikasi HP'), ('registration', 'Registrasi')], max_length=32)),
                ('phone', models.CharField(max_length=15)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Telepon',
                'verbose_name_plural': 'OTP Telepon',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='api_phoneot_user_id_5ce7b2_idx')],
            },
        ),
    ]
