# Generated by Django 5.2.15 on 2026-08-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_pdp_minimise_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontenedukasi',
            options={'ordering': ['-created_at'], 'verbose_name': 'Konten Edukasi', 'verbose_name_plural': 'Konten Edukasi'},
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Reset Password'), ('phone_verify', 'Verifikasi HP'), ('registration', 'Registrasi'), ('account_deletion', 'Hapus Akun')], max_length=32),
        ),
    ]
