# Generated by Django 5.2.15 on 2026-08-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_institusi_syarat_ketentuan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontenedukasi',
            options={'ordering': ['-created_at'], 'verbose_name': 'Konten Edukasi', 'verbose_name_plural': 'Konten Edukasi'},
        ),
    ]
