# Generated by Django 5.2.15 on 2026-08-18 08:54

from django.db import migrations, models


def add_column_if_missing(apps, schema_editor):
    """Tambahkan kolom hanya jika belum ada (reconcile drift DB lama)."""
    from django.db import connection

    table = 'api_pengaturaninstitusi'
    with connection.cursor() as cursor:
        columns = [
            col.name
            for col in connection.introspection.get_table_description(
                cursor, table,
            )
        ]
    if 'syarat_ketentuan' not in columns:
        model = apps.get_model('api', 'PengaturanInstitusi')
        field = models.TextField(blank=True, default='')
        field.set_attributes_from_name('syarat_ketentuan')
        schema_editor.add_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_kontenedukasi_options_alter_phoneotp_purpose'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='pengaturaninstitusi',
                    name='syarat_ketentuan',
                    field=models.TextField(
                        blank=True,
                        default='',
                        help_text='Markdown syarat & ketentuan (web publik & admin).',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_column_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
        ),
    ]
