# Generated by Django 5.2.15 on 2026-08-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_kontenedukasi_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Reset Password'), ('phone_verify', 'Verifikasi HP'), ('registration', 'Registrasi'), ('account_deletion', 'Hapus Akun')], max_length=32),
        ),
    ]
