# Generated by Django 5.2.15 on 2026-09-25 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_phoneotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='kategori',
            field=models.CharField(choices=[('setoran', 'Setoran'), ('penjemputan', 'Penjemputan'), ('penarikan', 'Penarikan Saldo'), ('penukaran', 'Penukaran Poin'), ('pengaduan', 'Pengaduan'), ('pengumuman', 'Pengumuman'), ('harga', 'Perubahan Harga'), ('jadwal_jemput', 'Jadwal Penjemputan'), ('sistem', 'Sistem')], default='sistem', max_length=20),
        ),
        migrations.CreateModel(
            name='JadwalJemputWilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('catatan', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wilayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_jemput', to='api.wilayahlayanan')),
            ],
            options={
                'verbose_name': 'Jadwal Jemput Wilayah',
                'verbose_name_plural': 'Jadwal Jemput Wilayah',
                'ordering': ['tanggal', 'jam_mulai'],
            },
        ),
        migrations.AddField(
            model_name='penjemputan',
            name='jadwal_wilayah',
            field=models.ForeignKey(blank=True, help_text='Jadwal jemput wilayah yang dipilih nasabah.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penjemputan', to='api.jadwaljemputwilayah'),
        ),
        migrations.AddIndex(
            model_name='jadwaljemputwilayah',
            index=models.Index(fields=['tanggal'], name='api_jadwalj_tanggal_27241f_idx'),
        ),
        migrations.AddConstraint(
            model_name='jadwaljemputwilayah',
            constraint=models.UniqueConstraint(fields=('wilayah', 'tanggal'), name='uniq_jadwal_jemput_wilayah_tanggal'),
        ),
    ]
