# Generated by Django 5.2.15 on 2026-09-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_jadwal_jemput_wilayah'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='email_exempt',
            field=models.BooleanField(default=False, help_text='Akun dibuat admin tanpa email — tidak wajib verifikasi email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True jika email sudah diverifikasi OTP email'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('email_verify', 'Verifikasi Email'), ('password_reset', 'Reset Password'), ('phone_verify', 'Verifikasi HP'), ('registration', 'Registrasi'), ('account_deletion', 'Hapus Akun')], max_length=32),
        ),
    ]
