# Generated by Django 5.2.15 on 2026-09-25 08:37

from django.db import migrations, models


def isi_wilayah_resmi(apps, schema_editor):
    """14 kelurahan/kampung resmi Distrik Mimika Baru; nonaktifkan yang di luar distrik.

    Nasabah yang terhubung ke wilayah nonaktif dikosongkan kelurahannya agar
    memilih ulang (alamat teks tetap). Riwayat jadwal/penjemputan tidak diubah.
    """
    from api.services.wilayah import KELURAHAN_MIMIKA_BARU, upsert_kelurahan

    WilayahLayanan = apps.get_model('api', 'WilayahLayanan')
    User = apps.get_model('api', 'User')
    upsert_kelurahan(WilayahLayanan, KELURAHAN_MIMIKA_BARU)
    resmi = {nama.lower() for _, nama in KELURAHAN_MIMIKA_BARU}
    luar = [
        w.pk for w in WilayahLayanan.objects.all()
        if w.kelurahan.strip().lower() not in resmi
    ]
    WilayahLayanan.objects.filter(pk__in=luar).update(aktif=False)
    User.objects.filter(kelurahan_id__in=luar).update(kelurahan=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilayahlayanan',
            name='jenis',
            field=models.CharField(blank=True, choices=[('kelurahan', 'Kelurahan'), ('kampung', 'Kampung')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='wilayahlayanan',
            name='kode',
            field=models.CharField(blank=True, help_text='Kode Kemendagri kelurahan/kampung (mis. 94.04.01.1001)', max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(isi_wilayah_resmi, migrations.RunPython.noop),
    ]
