# Generated by Django 5.2.15 on 2026-09-30 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_wilayah_resmi_mimika_baru'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjemputan',
            name='setoran',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penjemputan', to='api.transaksisetoran'),
        ),
    ]
