# Generated by Django 5.2.15 on 2026-09-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_penjemputan_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='penarikansaldo',
            name='alasan_penolakan',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='penjemputan',
            name='alasan_penolakan',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='penukaranpoin',
            name='alasan_penolakan',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
